services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: rewards-app
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=reward_system
      - DB_USERNAME=root
      - DB_PASSWORD=qazwsx
    networks:
      - rewards

  mysql:
    image: mysql:5.7
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: reward_system
      MYSQL_ROOT_PASSWORD: qazwsx
    volumes:
      - rewards-mysql:/var/lib/mysql
    networks:
      - rewards

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - rewards
      
networks:
  rewards:
    driver: bridge

volumes:
  rewards-mysql:
    driver: local
  redis_data:
  
