services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: rewards-app
    ports:
      - 8000:8000
    depends_on:
      - mysql
    environment:
      - DB_HOST=rewards-mysql
      - DB_PORT=3306
      - DB_DATABASE=reward_system
      - DB_USERNAME=root
      - DB_PASSWORD=qazwsx
    networks:
      - rewards
    entrypoint: ["/bin/sh", "-c"]
    command: >
      composer install &&
      php artisan migrate &&
      php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:5.7
    container_name: rewards-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: reward_system
      MYSQL_USER: root
      MYSQL_PASSWORD: qazwsx
      MYSQL_ROOT_PASSWORD: qazwsx
    volumes:
      - rewards-mysql:/var/lib/mysql
    networks:
      - rewards

networks:
  rewards:
    driver: bridge

volumes:
  rewards-mysql:
    driver: local
